name: Daily Free Fire Log

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FREEFIRE_UID: "2805365702"
      CSV_PATH: "freefire_daily.csv"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetcher
        run: |
          python fetch_and_append.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$CSV_PATH"
          git diff --staged --quiet || git commit -m "Daily update: freefire log"
          git push
