name: Daily Free Fire Log

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FREEFIRE_UID: "2805365702"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run fetcher
        run: |
          python scripts/fetch_and_append.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          MONTHLY_FILE=$(python - <<'PY'
          from datetime import datetime
          from zoneinfo import ZoneInfo

          now = datetime.now(ZoneInfo("Asia/Colombo"))
          print(f"{now.year} {now.strftime('%m')}.CSV")
          PY
          )
          git add -- "summary.csv" "$MONTHLY_FILE"
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily update: freefire log"
            git pull --rebase origin "$GITHUB_REF_NAME"
            git push
          fi
