name: Free Fire Likes Booster

on:
  schedule:
    - cron: "30 18 * * *"
    - cron: "0 19 * * *"
    - cron: "30 19 * * *"
    - cron: "0 20 * * *"
    - cron: "30 20 * * *"
    - cron: "0 21 * * *"
    - cron: "30 21 * * *"
    - cron: "0 22 * * *"
    - cron: "30 22 * * *"
    - cron: "0 23 * * *"
    - cron: "30 23 * * *"
    - cron: "0 0 * * *"
    - cron: "30 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  give-likes:
    runs-on: ubuntu-latest
    env:
      FREEFIRE_LIKES_UID: "2805365702"
      FREEFIRE_LIKES_KEY: "astute2k3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Attempt to send likes
        run: |
          python scripts/send_likes.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -- "likes_activity.csv"
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated likes update"
            git pull --rebase origin ""
            git push
          fi
